### ISSUE TITLE
v24 Reds Checklist

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/MP3_Trigger#2]
ISSUES:
(1) The TRIG17 and TRIG18 nets need flag labels

(2) DPDT and Nav switches both have "U" as the prefix, should be "S"

(3) This might be the same issue that I mentioned on the proto checklist, if so, please omit: There is a clearance issue thrown on one of the vias under the PSoC. I have my DRC clearances set to 6 mil min.

(4) Looks like NAV switch and barrel need tNames and tValues elements in the BRD

Concerns/comments:
(1) Might be worth noting AC and DC coupled on the jumper key on the back of the board

(2) There are a couple instances throughout the design of traces exiting pads at an angle. While I don't think any of the examples would cause functional issues with the design, I think they are worth fixing before we order REDs quantities. IMO

(3) According to the checklist, BLUE is the standard color we want to use for "STAT" LEDs. The stat LED in the design is green. I know there is a lot of documentation and support stuff on both Jamie's side and our's that reference the GREEN stat LED in the design. On that note, I think changing the LED to BLUE would be more trouble than it is worth. This is more of a CYA to show it was thought of.

(4) Looks like the design contains mostly 10 mil traces, but there are some 8 mil traces sprinkled around. I understand using smaller traces if a smaller pad necessitates it, but I can't see the reasoning for some of the 8 mil traces in the design. eg. See the "T" intersection on the "3.3V" trace near the R12 resistor. Again, I don't think function will be affected if the design stays as is, but I think it would make the design better to eliminate un-necessarily small trace widths. IMO

That's it.

**Comment by JoelEB** [comment]
1) Fixed
2) Renamed
3) Fixed
4) Not sure what you mean. Is this the same issue we had that was just different on my computer vs yours? 

1) Added
2)Tried to get as many as I could
3) I'm not changing the LED at this stage.
4) bumped up as many as I could to 10 mil
