### ISSUE TITLE
Parallel play of multiple Files

### ISSUE THREAD

**Issue by hedior03** [sparkfun/MP3_Trigger#3]
I Would like to play a sound after every interrupt on a system, but I need that the playing of each instance of every sound continue until finish each file, Is it possible with this device or exists a firmware wich could afford this?

**Comment by nseidle** [comment]
The MP3 trigger can only play one song at a time but the [Tsunami](https://www.sparkfun.com/products/13810) can play up to 32 mono tracks at the same time, starting and stopping independently.
